### ISSUE TITLE
Auto switch Audience display from Match Play to Blank at end of match

### ISSUE THREAD

**Issue by FletcherS7** [Team254/cheesy-arena#101]
Add Automatic switching of the Audience display from the Match Play overlay to the Blank overlay at the end of a match, Since the scorekeeper currently does this manually.

**Comment by patfair** [comment]
Not sure I understand the ask -- is it something different than this existing functionality? https://github.com/Team254/cheesy-arena/blob/master/field/arena.go#L436

**Comment by FletcherS7** [comment]
I'm dumb. I never noticed that and thought it was the same as FIRST FMS.
