### ISSUE TITLE
Bootstrap is still using version 3

### ISSUE THREAD

**Issue by baconstrip** [Team254/cheesy-arena#114]
Ideally, we'd want to update to a newer version of bootstrap that uses more modern styles and supports more features (for example button groups). 

I'm happy to do the work myself to upgrade to this verison (as there's many breaking changes in versions 4 and 5), but I'm wondering if you'd accept a change that upgrades the libraries and updates the UI change to use the new library (with the pages matching as closely as possible to existing pages).

Thanks.

**Comment by patfair** [comment]
Absolutely; I'd welcome that change. I haven't done it myself only because I generally follow an "if it ain't broke" prioritization strategy.

**Comment by patfair** [comment]
This is happening for the 2024 version.
