### ISSUE TITLE
Endgame sounds don't play in practice matches

### ISSUE THREAD

**Issue by CrispyBacon1999** [Team254/cheesy-arena#118]
We're using cheesy arena for a scrimmage and found that the 30 second warning sound doesn't actually play.

**Comment by ebot1234** [comment]
What is your setup? Did the other sounds play as normal?

**Comment by CrispyBacon1999** [comment]
We're mostly just using it for scoring and timing, but all other sounds work perfectly fine. Only missing sound is endgame, and even manually pressing it during the match from match test doesn't fix it. (It does work if you press warning outside of a match)

**Comment by ebot1234** [comment]
I would check in the static/audio folder to see if the warning.wav is present. If it is, I would try reinstalling CA or building from the source again.

**Comment by CrispyBacon1999** [comment]
It does work fine from the field test, and the file is in the right place. Not sure if it's just configured to play at the wrong time or something.

**Comment by ebot1234** [comment]
Yeah, that could be it. There are timing settings in the setup tab that can change when that sound is called.

**Comment by ebot1234** [comment]
@patfair Any Ideas?

**Comment by CrispyBacon1999** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/6081500/162849982-5aba770a-af13-4940-ac39-19f913fd7432.png">
Times all look correct to me

**Comment by ebot1234** [comment]
Yeah, I'm not sure what would be wrong. I can't reproduce the issues on my end but maybe Pat will have more insight later. 
Did you build CA from scratch or use the precompiled version?

**Comment by CrispyBacon1999** [comment]
Precompiled on M1

**Comment by ebot1234** [comment]
It might work if you tried rebuilding it using the source. I've fixed problems with my versions of CA by doing so.

**Comment by CrispyBacon1999** [comment]
Yeah, I'll give that a try

**Comment by CrispyBacon1999** [comment]
Ok, so it seems like it's not an actual issue, that sound effect is just EXTREMELY quiet compared to everything else.

**Comment by ebot1234** [comment]
Oh okay, that works too.
