### ISSUE TITLE
Can't generate match schedule (2015 release)

### ISSUE THREAD

**Issue by TheBassett** [Team254/cheesy-arena#12]
Added 25 teams to the teams list then tried to generate a match schedule (as shown in the screenshot):
![issuecheesyarena](https://cloud.githubusercontent.com/assets/7651738/10184171/baa971b2-6706-11e5-95ae-724446899a52.PNG)

After clicking the "Generate Schedule" button it throws up the "Incomplete or invalid schedule block parameters specified." error message. I followed along with the demo video so I don't believe I missed any steps - correct me if I'm wrong.

**Comment by bkeeneykid** [comment]
Also getting this issue. Is this in the processor of being fixed or is it even acknowledged?

**Comment by patfair** [comment]
I wasn't able to reproduce this issue, but it sounds like something JavaScript-related. What browser is this being seen on?

**Comment by TheBassett** [comment]
I originally tested this on chrome. I tried the same setup I had before (CA saved the teams list) and it works now - it was problably just a bug in chrome. @bkeeneykid If you're using Chrome, is it up to date?

**Comment by bkeeneykid** [comment]
I now use Safari 8 on Mac. I'll try Chrome later.

**Comment by phil-lopreiato** [comment]
@patfair I can reproduce the issue on Firefox 42/Fedora 23. Didn't see any JS errors, but I'm not familiar enough to debug thoroughly. It does however work properly for me on Chrome 46

**Comment by patfair** [comment]
I figured out the root cause -- Firefox can't parse dates that use a hyphen as the separator. Officially only Chrome is supported, but I'll fix this eventually.

**Comment by rich-coe** [comment]
I reproduced this issue on linux with chrome Version 48.0.2564.109 (64-bit)
I tried the same chrome version on windows and it works.
