### ISSUE TITLE
Add Timeout 1 Minute remaining warning sound effect

### ISSUE THREAD

**Issue by FletcherS7** [Team254/cheesy-arena#121]
Add the sound effect that plays when 1 minute of a timeout is remaining.
I am able to provide the wav file if needed.

**Comment by patfair** [comment]
Sure, this sounds reasonable. Please do provide the wav.

**Comment by FletcherS7** [comment]
[TimeoutWarning.zip](https://github.com/Team254/cheesy-arena/files/8484958/TimeoutWarning.zip)
