### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by arnon001** [Team254/cheesy-arena#123]
Is it possible to add the Plane that flying and telling the winning alliance?,
its important to me so I will be able to make the winning like the regular game

**Comment by patfair** [comment]
It isn't a goal of Cheesy Arena to imitate the visual interfaces of the official FMS, so we won't be doing this (not to mention the potential copyright issues in doing so).

You are of course always free to fork Cheesy Arena and implement it yourself.
