### ISSUE TITLE
Add simple foul mode for ref panel

### ISSUE THREAD

**Issue by FletcherS7** [Team254/cheesy-arena#132]
Add an event option that simplifies the referee screen to just adding or removing red and blue fouls/tech fouls.
This has been requested by several head refs because this is how fouls are input from the FIRST FMS ref panels.

**Comment by patfair** [comment]
Done in https://github.com/Team254/cheesy-arena/commit/baa96b1435c597fa275e2f6111b62ab73f55ea0a.
