### ISSUE TITLE
Double Elimination Improvements

### ISSUE THREAD

**Issue by FletcherS7** [Team254/cheesy-arena#133]
Swap Match 11 and 12
Match 11 should be Winners of Match7 and Match8
Match 12 should be Winners of Match10 and Match9
This removes the need for a timeout period between Round 3 and Round 4 since no teams will have a back to back match.

Add logic to playoff scheduling to automatically schedule times with 15min minimum between an alliances matches.

Enable the "Field Running" status in Double Elimination mode on field monitor, match play, etc

**Comment by patfair** [comment]
We'll defer to FIRST on the Match 11/12 swap and change it if they change it; the timeout/playoff committee has been given the team/spectator feedback from Chezy Champs. For context there's also discussion about the tradeoffs here: https://www.chiefdelphi.com/t/thoughts-on-double-elimination-for-frc/415439/35

**Comment by FletcherS7** [comment]
Playoff Schedule report should include all playoff matches and scheduled times, with the future matches being blank so they can be filled in as the bracket progresses.

**Comment by FletcherS7** [comment]
3d4c6b9 Resolves the rules of Double Eliminations.

### Additional improvements

Enable the "Field Running" status in Double Elimination mode on field monitor, match play, etc

Update playoff scheduling times to match official double elim schedule and add this schedule as a report (with future matches blank), also publish timings to TBA.
![image](https://user-images.githubusercontent.com/10507571/227098676-687293eb-b4ad-4175-aed1-b30855174e4e.png)
