### ISSUE TITLE
Player station lighting and displays info

### ISSUE THREAD

**Issue by themacman** [Team254/cheesy-arena#15]
We are looking into using Cheesy Arena for a practice field that we plan on holding scrimmages on and thus we would love to outfit our player stations with the arena displays. I saw in the Readme that there were plans to release schematics, software, and a BOM in a future release. Is there any plans to release those anytime soon?

**Comment by neyre** [comment]
Over the summer, we will be revisiting all of this equipment in preparation for Chezy Champs. We hope to get this better documented during this time.

**Comment by themacman** [comment]
Thanks! Looking forward to seeing it.
