### ISSUE TITLE
Playoff Match ties

### ISSUE THREAD

**Issue by cpapplefamily** [Team254/cheesy-arena#150]
Per Table 11-4 in the 2023 FRC game Manual the 4th option is to replay the match. Although this is VERY unlikely and I wonder if it happened at all this past season there still remains a possibility. I found that the current CA does not schedule a Replay match but simply moves on to the next match. The result is a playoff bracket without teams moving on. 

There is a work around and this maybe the intended option to load the Tie-ed match (Highlighted Yellow not Red) and re-run the match. I don't recall if this was the way the system worked in the past. The Finals matches do schedule overtime matches as expected. 

I discovered this while testing my 4 and 6 team double eliminations hack of CA

**Comment by patfair** [comment]
My reading of the manual is that "replay" means loading up the same match and playing it again, rather than a new one being generated. The official FMS also doesn't generate separate replay matches; the overtime ones are deliberately scheduled up front but just hidden until they are needed.
