### ISSUE TITLE
Update referee panel without refresh

### ISSUE THREAD

**Issue by andrewda** [Team254/cheesy-arena#18]
The referee panel should be updated using websockets to display penalties and cards applied by other referees without needing to be refreshed.

To make this work even smoother, you would ideally also use websockets to submit fouls/cards instead of submitting a form and refreshing the page.

**Comment by patfair** [comment]
Done in https://github.com/Team254/cheesy-arena/commit/baa96b1435c597fa275e2f6111b62ab73f55ea0a.
