### ISSUE TITLE
2024 Red and Blue scoring not working

### ISSUE THREAD

**Issue by Lego56371** [Team254/cheesy-arena#184]
Right now when I open the red and blue scoring panel this pops up. 
![Cheesy-Arena-Issue](https://github.com/Team254/cheesy-arena/assets/122835439/b61f963b-2686-40a9-ae91-a037a8afd7ef)

**Comment by patfair** [comment]
The `2024` branch is a development branch and implementation of the 2024 game is still in progress. Once its changes are merged into the `main` branch it'll be ready for use.
