### ISSUE TITLE
Match Logs

### ISSUE THREAD

**Issue by agdespopoulos** [Team254/cheesy-arena#2]
First of all, this is a great project, thanks for doing this and releasing it.  I was looking into viewing logs from matches, but when I run it on my computer, they are empty.  The log files are generated, but they don't have any data, but this makes sense since I bypassed all the robots (since I don't actually have any).  Do you have any sample logs (maybe from Chezy Champs) I can look at?

**Comment by neyre** [comment]
Two years late, but I've attached an example log file from this year's Chezy Champs.

[20160924100059_qualification_match_3_254.txt](https://github.com/Team254/cheesy-arena/files/496117/20160924100059_qualification_match_3_254.txt)
