### ISSUE TITLE
Cheesy Arena for Steamworks?

### ISSUE THREAD

**Issue by onenerdyguy** [Team254/cheesy-arena#38]
Will one be made? I know, loaded question. We're hoping to use it for an unofficial week 0

**Comment by patfair** [comment]
One will be made, but not before the end of the official competition season. Right now there's no time, and it's not yet clear what changes to the official rules will be desired for Chezy Champs and other events.

**Comment by onenerdyguy** [comment]
Works for me. Thanks!

-Bob Henderson-
Technology Coordinator
Robotics Coach
Lake Park Audubon Schools
218.238.5914 ext 2030
www.lakeparkaudubon.com
Check us out on Facebook! <http://www.facebook.com/lpa2889>

On Thu, Jan 19, 2017 at 11:49 AM, Patrick Fairbank <notifications@github.com

**Comment by patfair** [comment]
The 2017 version is pretty much done, and can be built from the source of the master branch. I'll wait until after Chezy Champs before releasing binaries.
