### ISSUE TITLE
Are ports 5801 -5810 permitted in cheesy arena?

### ISSUE THREAD

**Issue by mddrouillard** [Team254/cheesy-arena#42]
The official field permits communication between the ds and the robot wired clan on tcp ports 5801 thru 5810 as well as port 80. Is this currently implemented in the project?  I think if I need to add this it would be modify access list 111 through 116 on the. Switch?

**Comment by patfair** [comment]
I don't believe the current switch configs are disallowing any ports at all between the DS and robot. The 111-116 ACLs are to restrict traffic between the team VLANs and the field VLAN, but there shouldn't be any restriction within each VLAN.

**Comment by patfair** [comment]
Closing as inactive.
