### ISSUE TITLE
"No valid version found"

### ISSUE THREAD

**Issue by JamieSinn** [Team254/cheesy-arena#44]
After compiling for windows, seems like there's some unlisted prereqs. 
http://i.imgur.com/sueHzxK.png

Above is server 2012 r2.

Is VCC redist required? Or some other library? As running this on my desktop works fine, which is odd.

**Comment by rich-coe** [comment]
The message is coming from the cheesy-arena program.
Searching the dependencies, it is coming from goose.
I suspect you may an event.db in the current directory that cheesy-arena cannot read.
If this is the first time running the program, I'd remove it.  Otherwise, rename the file and try again.

**Comment by JamieSinn** [comment]
There is no event.db file in the current dir. Running CMD as admin gives the same error. And yes, this is the first time running it.

**Comment by themacman** [comment]
I'm hitting that on Linux (Ubuntu 16.04 LTS) too. I've gotten around it by cd'ing to the directory where the executable is and then putting the entire thing inside apostrophes, but I haven't been able to get much further (I straight up can't get the switch and AP to talk to the computer no matter what). Maybe this issue and that are related?

**Comment by patfair** [comment]
Are you running cheesy-arena.exe from the same directory it was compiled into? There's a runtime dependency on the db/migrations directory to define the DB structure the first time it is created.

**Comment by JamieSinn** [comment]
Ah, there we go. 
That would be the problem. Thanks Pat.

Would be a good addition to the readme.
