### ISSUE TITLE
Cheesy Arena FTA notepad. 

### ISSUE THREAD

**Issue by MrLtMajor** [Team254/cheesy-arena#58]
This year FIRST acquired a handy dandy app called FTA Notepad. This app is both a field monitor and allows adding notes to teams. the note then shows up when that team is on the field. The notes are also shared to everyone else connected to the API running on FMS.

Would it be possible to develop a version of this app for Cheesy Arena?

**Comment by MrLtMajor** [comment]
Here's the Google Play link and App Store link.
https://play.google.com/store/apps/details?id=com.wix.ftanotepad18.ftanp
https://itunes.apple.com/us/app/fta-notepad/id973382797?mt=8

**Comment by FS790746** [comment]
+1 for this.

**Comment by patfair** [comment]
I added an "FTA" configuration variant to the Field Monitor with functionality to keep notes on teams. I don't think we'll ever develop mobile applications vs a webpage, so hopefully that's good enough to close this issue.
