### ISSUE TITLE
Can you release a Windows version too this year?

### ISSUE THREAD

**Issue by YeveRivkin** [Team254/cheesy-arena#60]

**Comment by ebot1234** [comment]
You know you can compile all the source code pretty easily for windows. All the info on how to do that I'm pretty sure is in the wiki.
-Ethen

**Comment by patfair** [comment]
I can't release a Windows version since I don't own a Windows computer, but if someone else can help me out I'll gladly upload the zip to the release.

**Comment by ebot1234** [comment]
I can do it if you want, I have previously compiled the code for windows.
-Ethen
ebot14rocks@gmail.com

**Comment by patfair** [comment]
Awesome, that would be great. Probably won't be releasing anything until September, though.

**Comment by ebot1234** [comment]
Ok, cool.

**Comment by patfair** [comment]
I just uploaded a release for macOS, so if someone wants to create a Windows zip now I'd be happy to add it.

I tried out Go's nifty cross-compilation capability, but unfortunately the sqlite driver I'm using has dependencies on C code that is much harder to cross-compile.

**Comment by themacman** [comment]
Cool, I'll see about doing a Windows build sometime this week. If someone has more downtime than me, feel free to beat me to it.

**Comment by themacman** [comment]
Can we close?
