### ISSUE TITLE
Awards mode

### ISSUE THREAD

**Issue by ebot1234** [Team254/cheesy-arena#61]
Hey, can you make an awards mode for the leds, like the awards mode for the standard fms. The lights would just show red and blue on each element on the field, kind of what is happening during a match. Thanks

**Comment by patfair** [comment]
By this you mean just a mode where the lights stay solid red and blue indefinitely, regardless of sensor input or anything? Sure, we already have a bunch of test patterns implemented and can add one for this.

**Comment by ebot1234** [comment]
Yes, that is what it would need to be.
Thanks
-Ethen

**Comment by patfair** [comment]
There are now a bunch of test modes to choose from that should fit the bill.
