### ISSUE TITLE
FTA Display

### ISSUE THREAD

**Issue by ejordan376** [Team254/cheesy-arena#63]
Can you bring back the FTA display from the 2017.1.2 version, also keep the existing field monitor.

**Comment by patfair** [comment]
Yeah, I'll get something in place by Beach Blitz.

**Comment by FletcherS7** [comment]
looks good.
@ejordan376 Can you add the fuchsia color we tested at CalGames to the display?

**Comment by FletcherS7** [comment]
@patfair Would it be possible to sill restore the 2017 FTA display?

**Comment by patfair** [comment]
Is there any particular feature you want from the previous FTA display that is missing from the field monitor? Next year I'm planning to add an additional page with more textual data, like team notes and event logs, so I'd prefer to avoid ending up with three different displays.

**Comment by FletcherS7** [comment]
low battery voltage level in pre match state should be anything below 12v
low battery voltage level during match play should be 6v and below

**Comment by themacman** [comment]
The following may be helpful to when figuring out what you want/don't want to implement:

[FIRST FMS Match Log Interface](http://wpilib.screenstepslive.com/s/fms/m/fieldmonitor/l/591663-viewing-match-logs)

[FIRST FMS Field Monitor](http://wpilib.screenstepslive.com/s/fms/m/fieldmonitor/l/592785-live-monitor)

Screenshot from FIRST's FTA Notepad:
![image](https://user-images.githubusercontent.com/7830868/47800832-54ac0480-dd03-11e8-87c3-6696864fe281.png)
