### ISSUE TITLE
Add option to Reload match

### ISSUE THREAD

**Issue by FletcherS7** [Team254/cheesy-arena#94]
Cheesy Arena does pre starting when the match is loaded unlike FIRST FMS which has pre start as a separate step. Add ability to Reload a match (the current work around is to load a test match then load the match again)

**Comment by patfair** [comment]
Which particular problem are you trying to fix by reloading the match? Depending on what it is, we may be able to fix it either by just clicking the "Load" button for that match again, or by adding an internal feedback loop.

**Comment by FletcherS7** [comment]
It's not a particular problem. It's best described a network initialization problem.
This is a problem found with FIRST FMS as well. 
**I** think it's related to the radios, but who knows, "Pre Starting" fixes it.

**Comment by FletcherS7** [comment]
Still encountering cases where we need to load a test match, then load the current match again.
Low priority on this request, But I still think a reload match option would be useful.

**Comment by FletcherS7** [comment]
@patfair 
Currently clicking the load match button again does not re initialization the match and the field network. Would it be possible to change the behavior so it does? or add another button that does that.

Still running into problems that require loading a test match and then loading into the match again.
